table Forecast
	lineageTag: 230b4d40-907e-4ac8-844b-9408d3b64a1e

	column 'Account Number'
		dataType: int64
		formatString: 0
		lineageTag: 82a14ef7-b093-410d-9f59-4ebabbe1fd50
		summarizeBy: none
		sourceColumn: Account Number

		annotation SummarizationSetBy = Automatic

	column 'Amount (USD)'
		dataType: int64
		formatString: 0
		lineageTag: 82b3d9b9-8aca-4848-a330-8ab4f6c92594
		summarizeBy: sum
		sourceColumn: Amount (USD)

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 575a4ecc-25c8-45f8-a032-415bc52223c1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Forecast = m
		mode: import
		source =
				let
				    Source = Sql.Databases("xe6b73af6wce5cpkwv3dpk3vzi-d3eexxnlcfeuvekhkfenm33jbm.datawarehouse.fabric.microsoft.com"),
				    dw_dezerius_demo_client = Source{[Name="dw_dezerius_demo_client"]}[Data],
				    dbo_Forecast = dw_dezerius_demo_client{[Schema="dbo",Item="Forecast"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Forecast,{{"Account Number", Int64.Type}, {"Account Name", type text}, {"Amount (USD)", Int64.Type}, {"Month", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Month"}, #"Date DIM", {"Month ID"}, "Date DIM", JoinKind.LeftOuter),
				    #"Expanded Date DIM" = Table.ExpandTableColumn(#"Merged Queries", "Date DIM", {"Date"}, {"Date"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Date DIM",{"Account Name", "__PowerAppsId__", "Month"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

