table Account
	lineageTag: 6a137d70-a15c-43ac-b4da-c86ad99351bf

	column 'Account Number'
		dataType: int64
		formatString: 0
		lineageTag: b576490f-35a2-4e39-b363-6a49d9f2a102
		summarizeBy: none
		sourceColumn: Account Number

		annotation SummarizationSetBy = Automatic

	column 'Amount (USD)'
		dataType: int64
		formatString: 0
		lineageTag: c4c279e3-7bf5-489d-ae41-0f830ddf9bdd
		summarizeBy: sum
		sourceColumn: Amount (USD)

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6deb1d23-47ce-4700-b0bd-fbcbe28f4175
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Account = m
		mode: import
		source =
				let
				    Source = Sql.Databases("xe6b73af6wce5cpkwv3dpk3vzi-d3eexxnlcfeuvekhkfenm33jbm.datawarehouse.fabric.microsoft.com"),
				    dw_dezerius_demo_client = Source{[Name="dw_dezerius_demo_client"]}[Data],
				    dbo_Account = dw_dezerius_demo_client{[Schema="dbo",Item="Account"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Account,{{"Account Number", Int64.Type}, {"Account Name", type text}, {"Amount (USD)", Int64.Type}, {"Month", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Month"}, #"Date DIM", {"Month ID"}, "Date DIM", JoinKind.LeftOuter),
				    #"Expanded Date DIM" = Table.ExpandTableColumn(#"Merged Queries", "Date DIM", {"Date"}, {"Date"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Date DIM",{"Account Name", "Month"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

