/// Variance = P & L - Budget
/// 
table Calculations
	lineageTag: ce811be3-c915-4f81-9e80-0c56915904bc

	measure 'Amount P&L' = SUM( Account[Amount (USD)])
		formatString: 0
		displayFolder: Amounts
		lineageTag: 9bee9244-c5d6-4899-806e-a0f39010a8a4

	measure 'P & L items' = ```
			
			VAR _amount =  [Amount P&L]
			VAR _1 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 1)
			VAR _2 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 2)
			VAR _3 = 
			    _1 - _2
			VAR _4 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 4)
			VAR _5 = 
			    _3 - _4
			VAR _6 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 6)
			VAR _7 = 
			    _5 - _6
			RETURN
			
			IF( ISINSCOPE( 'coa DIM'[L3 Index]),
			    IF( SELECTEDVALUE( 'coa DIM'[L3 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L3 Index]), 'coa DIM'[Account Level] = 3)}, _amount),
			IF( ISINSCOPE( 'coa DIM'[L2 Index]),
			    IF( SELECTEDVALUE( 'coa DIM'[L2 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L2 Index]), 'coa DIM'[Account Level] = 2)}, _amount),
			IF( ISINSCOPE( 'coa DIM'[L1 Index]),
			            IF( SELECTEDVALUE( 'coa DIM'[L1 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L1 Index]), 'coa DIM'[Account Level] = 1)},
			            SWITCH( SELECTEDVALUE( 'coa DIM'[L1 Index]),
			            3,  _3,
			            5,  _5,
			            7,  _7,
			            _amount)
			            
			))))
			```
		displayFolder: Items
		lineageTag: e71f2d5b-e598-4c3d-aa30-d7ab59cc74c5

		formatStringDefinition = "€ 0K,"

	measure EBITDA = ```
			
			
			VAR _1 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 1)
			VAR _2 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 2)
			VAR _3 = 
			    _1 - _2
			VAR _4 = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 4)
			RETURN
			_3 - _4
			```
		formatString: #,0
		displayFolder: Amounts
		lineageTag: 76af535c-7f8d-4346-a293-9283cb51d29a

	measure 'Gross margin percentage' = ```
			
			
			VAR _rev = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 1)
			VAR _cogs = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 2)
			
			RETURN
			DIVIDE( _rev - _cogs, _rev )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Amounts
		lineageTag: ac4f8c1a-d557-4edc-9584-9e2ec441e0bf

	measure 'Overhead rate' = ```
			
			
			VAR _rev = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 1)
			VAR _oh = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 9)
			    
			RETURN
			DIVIDE( _oh , _rev)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Amounts
		lineageTag: b1d9e913-3188-4457-895a-286ccef1b166

	measure 'Revenue growth' = ```
			
			VAR _lastm = CALCULATE( 
			    SUM( Account[Amount (USD)])
			    , DATEADD( 'Date'[Date], - 1 , MONTH )
			    ,  'coa DIM' [L1 Index] = 1 
			)
			VAR _rev = 
			    CALCULATE( [Amount P&L], REMOVEFILTERS( 'coa DIM' ), 'coa DIM' [L1 Index] = 1)
			RETURN
			IF( 
			    ISBLANK( _lastm )
			     , "No data"
			     , (1 -  DIVIDE( _rev, _lastm )) * -1
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Amounts
		lineageTag: e38fe486-0b93-48eb-a6fe-a063b1216f93

	measure Title = "Profit & Loss Report"
		displayFolder: Labels & titles
		lineageTag: 634216da-2dfc-43ac-a7be-64ce649466ac

	measure 'EBITDA MoM' = ```
			
			VAR _ebita = [EBITDA]
			VAR _last = CALCULATE( [EBITDA], DATEADD( 'Date'[Date], -1, MONTH))
			RETURN
			IF( 
			    ISBLANK(_last)
			    , "No data"
			    ,DIVIDE( _ebita - _last, _last )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Amounts
		lineageTag: 0aee9799-a25a-4d49-8622-900905a4256c

	measure 'EBITDA card label' =
			
			IF( [EBITDA MoM] = "No data", "EBITDA",
			    IF( [EBITDA MoM] >= 0
			    ,"MoM " & "✅" & FORMAT( [EBITDA MoM], "##0.00%" )
			    ,"MoM " & "❗" & FORMAT( [EBITDA MoM], "##0.00%" )
			))
		displayFolder: Labels & titles
		lineageTag: 6d5849f3-b2ea-44b4-bce9-13f2cc151b11

	measure 'P & L items LM' =
			
			CALCULATE(
			    [P & L items], DATEADD( 'Date'[Date], -1, MONTH )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: Items
		lineageTag: 003222eb-42df-4a16-b645-9f850216c7e2

	measure 'Gross margin MoM' = ```
			
			VAR _grossm = [Gross margin percentage]
			VAR _last = CALCULATE( [Gross margin percentage], DATEADD( 'Date'[Date], -1, MONTH))
			RETURN
			IF( 
			    ISBLANK(_last)
			    , "No data"
			    ,DIVIDE( _grossm - _last, _last )
			)
			```
		displayFolder: Amounts
		lineageTag: b541f573-0e1c-43e6-81ae-2aecc26f6ed4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overhead MoM' = ```
			
			VAR _overh = [Overhead rate]
			VAR _last = CALCULATE( [Overhead rate], DATEADD( 'Date'[Date], -1, MONTH))
			RETURN
			IF( 
			    ISBLANK(_last)
			    , "No data"
			    ,DIVIDE( _overh - _last, _last )
			)
			```
		displayFolder: Amounts
		lineageTag: 50b57375-4b56-4383-95ce-945d2234f9b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross margin card label' =
			
			IF( [Gross margin MoM] = "No data", "Gross margin %",
			    IF( [Gross margin MoM] >= 0
			    ,"MoM " & "✅" & FORMAT( [Gross margin MoM], "##0.00%" )
			    ,"MoM " & "❗" & FORMAT( [Gross margin MoM], "##0.00%" )
			))
		displayFolder: Labels & titles
		lineageTag: b2ec5165-3af2-4c49-ab37-273701ef1711

	measure 'Overhead card label' =
			
			IF( [Overhead MoM] = "No data", "Overhead rate",
			    IF( [Overhead MoM] >= 0
			    ,"MoM " & "✅" & FORMAT( [Overhead MoM], "##0.00%" )
			    ,"MoM " & "❗" & FORMAT( [Overhead MoM], "##0.00%" )
			))
		displayFolder: Labels & titles
		lineageTag: b092d998-bb6f-4a80-a5f1-e2df41c95a71

	measure 'Revenue card label' =
			
			IF( [Revenue growth] = "No data", "Revenue growth MoM",
			    IF( [Revenue growth] >= 0.03
			    ,"Target : 3% " & "✅"
			    ,"Target : 3% " & "❗"
			))
		displayFolder: Labels & titles
		lineageTag: f59493e1-329b-4365-ba14-f01212bd9eb1

	measure 'EBITDA color rules' =
			
			IF(
			    [EBITDA] < 50000,
			    "#EF585D", "#1cd26d"
			)
		displayFolder: Support
		lineageTag: 170843c2-8863-4ae4-aaab-34f2ef9b9f28

	measure 'Subtitle Management site' = "Management Summary"
		displayFolder: Labels & titles
		lineageTag: 4a7f6904-6c47-49ec-bf31-0956daa9d562

	measure 'Subtitle Home site' = "Home page"
		displayFolder: Labels & titles
		lineageTag: a8948d72-1151-47d9-b341-a6f982b195cd

	measure 'Subtitle Detailed site' = "P & L Details"
		displayFolder: Labels & titles
		lineageTag: 9bdb8461-8a4a-43d5-be50-2ecda673da46

	measure 'Subtitle What If site' = "What-If Analysis"
		displayFolder: Labels & titles
		lineageTag: 2f12695d-5342-49c7-a070-6b844cbff0b8

	measure 'Amount Budget' = SUM( Budget[Amount (USD)])
		formatString: 0
		displayFolder: Amounts
		lineageTag: d3c34f02-5a70-475e-96dc-cfbad8f25886

	measure 'Budget items' = ```
			
			VAR _amount =  [Amount Budget]
			VAR _1 = 
			    CALCULATE( [Amount Budget], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 1)
			VAR _2 = 
			    CALCULATE( [Amount Budget], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 2)
			VAR _3 = 
			    _1 - _2
			VAR _4 = 
			    CALCULATE( [Amount Budget], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 4)
			VAR _5 = 
			    _3 - _4
			VAR _6 = 
			    CALCULATE( [Amount Budget], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L1 Index] = 6)
			VAR _7 = 
			    _5 - _6
			RETURN
			
			IF( ISINSCOPE( 'coa DIM'[L3 Index]),
			    IF( SELECTEDVALUE( 'coa DIM'[L3 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L3 Index]), 'coa DIM'[Account Level] = 3)}, _amount),
			IF( ISINSCOPE( 'coa DIM'[L2 Index]),
			    IF( SELECTEDVALUE( 'coa DIM'[L2 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L2 Index]), 'coa DIM'[Account Level] = 2)}, _amount),
			IF( ISINSCOPE( 'coa DIM'[L1 Index]),
			            IF( SELECTEDVALUE( 'coa DIM'[L1 Index]) IN {CALCULATE( VALUES( 'coa DIM'[L1 Index]), 'coa DIM'[Account Level] = 1)},
			            SWITCH( SELECTEDVALUE( 'coa DIM'[L1 Index]),
			            3,  _3,
			            5,  _5,
			            7,  _7,
			            _amount)
			            
			))))
			```
		displayFolder: Items
		lineageTag: 50228933-5e8a-4660-84e0-7e966614f607

		formatStringDefinition = "€ 0K,"

	/// Variance = P & L - Budget
	/// 
	measure 'Variance items' = [P & L items] - [Budget items]
		displayFolder: Items
		lineageTag: 7aa35dbe-625a-4fa1-853a-1b071d112d2a

		formatStringDefinition = "€ 0K,;(€ 0K),"

	measure 'Rows in Account' = COUNTROWS( Account )
		formatString: 0
		displayFolder: Support
		lineageTag: e3179f76-bb33-4b0f-a529-b37e4a8d41b1

	measure 'Act and Forcast EBITDA' = ```
			
			
			VAR _lastactdate = 
			CALCULATE( 
			    MAX( Account[Date]), REMOVEFILTERS()
			)
			
			VAR _act = [EBITDA]
			
			VAR _forecast = 
			CALCULATE( 
			    [EBITDA Forecast],
			    KEEPFILTERS( 'Date'[Date] > _lastactdate)
			)
			
			VAR _result = _forecast + _act
			
			RETURN
			_result
			```
		formatString: #,0
		displayFolder: Amounts
		lineageTag: bde07663-f7e8-4c4d-82b3-0f937840786d

	measure 'Amount Forecast' = SUM( Forecast[Amount (USD)])
		formatString: 0
		displayFolder: Amounts
		lineageTag: 284d0aff-dc40-4b13-a62f-0891f1e37f2e

	measure 'EBITDA Forecast' = ```
			
			
			VAR _1_2 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 2) * ( 1 + 'Revenue (Toys)'[Revenue (Toys) Value])
			VAR _1_3 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 3) * ( 1 + 'Revenue (Accessories)'[Sales Revenue (Accessories) Value])
			VAR _1_4 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 4) * ( 1 + 'Sales Revenue (Licensed Products)'[Sales Revenue (Licensed Products) Value])
			VAR _1_5 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 5) * ( 1 + 'Sales Revenue (Other)'[Sales Revenue (Other) Value])
			VAR _1 =
			    _1_2 + _1_3 + _1_4 + _1_5
			
			VAR _2_7 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 7) * ( 1 + 'Direct Materials'[Direct Materials Value])
			VAR _2_8 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 8) * ( 1 + 'Direct Labor'[Direct Labor Value])
			VAR _2_9 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 9) * ( 1 + 'Manufacturing Overhead'[Manufacturing Overhead Value])
			VAR _2 = 
			    _2_7 + _2_8 + _2_9
			    
			VAR _3 = 
			    _1 - _2
			    
			VAR _4_12 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 12) * ( 1 + 'Salaries and Wages'[Salaries and Wages Value])
			VAR _4_13 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 13) * ( 1 + 'Rent and Utilities'[Rent and Utilities Value])
			VAR _4_14 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 14) * ( 1 + 'Marketing and Advertising'[Marketing and Advertising Value])
			VAR _4_15 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 15)
			VAR _4_16 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 16)
			VAR _4_17 = 
			    CALCULATE( [Amount Forecast], REMOVEFILTERS( 'coa DIM' ), 'coa DIM'[L2 Index] = 17)
			VAR _4 = 
			    _4_12 + _4_13 + _4_14 + _4_15 + _4_16 + _4_17
			    
			RETURN
			
			_3 - _4
			```
		formatString: 0
		displayFolder: Amounts
		lineageTag: 5cc477ac-bfb6-404c-ad17-c2ff401f88a5

	measure 'What If explanation label' = "What-If Analysis is the process of changing variables to see how those changes will affect the outcome." & UNICHAR(10) & UNICHAR(10) & "👇 Try it out, change a parameter! 👇"
		displayFolder: Support
		lineageTag: 0e31a1ef-f943-4523-852d-6d35666c5fbc

	measure 'Home page text' =
			"Home page
			With these buttons you can navigate easily between the pages of the report."
		displayFolder: Support
		lineageTag: 1f3bdd06-e4d0-4f3b-9ede-859374ac28ca

	measure 'Summary text' = ```
			
			 "Management Summary page:
			 You can find here KPI cards for management, and a high level P & L chart."
			```
		displayFolder: Support
		lineageTag: 1eb457f8-c936-49b3-b15a-60e1a90a661f

	measure 'Details text' = ```
			
			 "P & L Details page:
			 You can find here the detailed P & L chart. You can choose from P & L, Budget and Variance columns.
			 Variance = P & L - Budget"
			```
		displayFolder: Support
		lineageTag: 44147648-e5be-4377-a8fb-9ed568a39d05

	measure 'What-If text' = ```
			
			 "What - If Analysis page:
			 You can find here What - If Analysis chart with a lot of parameter."
			```
		displayFolder: Support
		lineageTag: 2ef2d56d-c1cc-47a5-ad7b-fec301c6032a

	measure 'EBITDA frecast color rules' =
			
			IF(
			    [Act and Forcast EBITDA] < 50000,
			    "#EF585D", "#1cd26d"
			)
		displayFolder: Support
		lineageTag: 3cf7bdb4-3110-4170-9dc4-2b9eff50903b

	measure 'P&L variance center' =
			
			CALCULATE(
			    MAXX(
			        ALLSELECTED( 'coa DIM'[L1] ), [Amount P&L]
			    ) * 1.5,
			    REMOVEFILTERS( 'coa DIM')
			)
		displayFolder: Support
		lineageTag: 20c6ebf3-88a3-4b76-872a-eb61f3c303c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P & L CM vs LM' =
			
			[P & L items] - [P & L items LM]
		formatString: 0
		displayFolder: Items
		lineageTag: fd525b11-891c-4deb-8b96-a3bec308327f

	measure 'P & L CM vs LM pos' =
			
			IF(
			    [P & L items] >= [P & L items LM],
			    [P & L CM vs LM]
			)
		formatString: 0
		displayFolder: Items
		lineageTag: 98dc1fbe-4f91-45e4-acd0-627fb62c373b

	measure 'P&L variance center dummy' = [P&L variance center]
		displayFolder: Support
		lineageTag: ce8de344-b66e-4a92-bff0-2fefb1f40883

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P & L CM vs LM neg' =
			
			IF(
			    [P & L items] < [P & L items LM],
			    [P & L CM vs LM]
			)
		formatString: 0
		displayFolder: Items
		lineageTag: 09907070-fcf0-4895-8814-70d292406884

	measure 'Label position left' = ```
			
			IF( 
			    [P & L items] < [P & L items LM],
			    [P&L variance center] + [P & L CM vs LM]
			)
			```
		displayFolder: Support
		lineageTag: d06706f4-6989-4270-b9e1-f1a70c68391e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Label position right' = ```
			
			IF( 
			    [P & L items] > [P & L items LM],
			    [P&L variance center] + [P & L CM vs LM]
			)
			```
		displayFolder: Support
		lineageTag: 3232a708-c9a9-4d56-93d7-699423096df1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P & L CM vs LM perc' =
			
			DIVIDE(
			    [P & L items] - [P & L items LM] , [P & L items]
			)
		displayFolder: Items
		lineageTag: 6e807359-87f7-49c4-b184-1aa9a0119a0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P & L CM vs LM perc neg' =
			
			IF(
			    [P & L items] < [P & L items LM],
			    [P & L CM vs LM perc]
			)
		displayFolder: Items
		lineageTag: c4722cad-244f-47ea-b47b-0e1e3289144d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P & L CM vs LM perc pos' =
			
			IF(
			    [P & L items] >= [P & L items LM],
			    [P & L CM vs LM perc]
			)
		displayFolder: Items
		lineageTag: 78f81f37-4f0f-4f03-84d4-49a5aba36df8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Drillthr titel' = "Lower level"
		displayFolder: Labels & titles
		lineageTag: 5122a65a-1b7c-4250-b4f9-1c852bd1493a

	measure 'EBITDA color rules for bar' =
			
			IF(
			    [EBITDA] < 50000,
			    "#DE6A73", "#5DB241"
			)
		displayFolder: Support
		lineageTag: ef207561-a5ac-4cf2-9a8a-ede681083158

	measure 'Subtitle Better on laptop' = "Better to see this page on your laptop 😁"
		displayFolder: Labels & titles
		lineageTag: 27318122-649c-412e-89df-bc95e8977391

	column Column1
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9d5532e8-6a61-4154-a633-86f031f74be4
		summarizeBy: sum
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

